
export const GET_CUSTOMER_NAMES = 'GET_CUSTOMER_NAMES';
export const GET_CUSTOMER_DETAILS_BY_NAME = 'GET_CUSTOMER_DETAILS_BY_NAME';

export const GET_CUSTOMER_NAME = 'GET_CUSTOMER_NAME';

//constant
export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAIL = 'FETCH_CUSTOMERS_FAIL';